version: "3"

# Taskfile for sess
# A modern alternative to Makefile using Task (task.dev)

vars:
  BINARY_NAME: sess
  BUILD_DIR: .
  # Install to standard Go bin directory
  INSTALL_DIR: "{{.HOME}}/go/bin"
  CMD_DIR: ./cmd/session
  # Use shell commands for dynamic variables
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"

tasks:
  # Default task - runs when you just type "task"
  default:
    desc: Build the sess binary (default)
    cmds:
      - task: build

  build:
    desc: Build the sess binary
    cmds:
      - echo "Building {{.BINARY_NAME}}..."
      - go build -ldflags "-X main.Version={{.VERSION}} -X main.Commit={{.COMMIT}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.CMD_DIR}}
      - echo "Build complete{{":"}} {{.BUILD_DIR}}/{{.BINARY_NAME}}"
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"

  test:
    desc: Run all tests
    cmds:
      - echo "Running tests..."
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - echo "Running tests with coverage..."
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report{{":"}} coverage.html"
    generates:
      - coverage.out
      - coverage.html

  install:
    desc: Build and install to ~/go/bin
    deps:
      - build
    cmds:
      - echo "Installing {{.BINARY_NAME}} to {{.INSTALL_DIR}}..."
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.INSTALL_DIR}}/{{.BINARY_NAME}}
      - chmod +x {{.INSTALL_DIR}}/{{.BINARY_NAME}}
      - echo "Installed{{":"}} {{.INSTALL_DIR}}/{{.BINARY_NAME}}"

  clean:
    desc: Remove build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -f {{.BUILD_DIR}}/{{.BINARY_NAME}}
      - rm -f coverage.out coverage.html
      - echo "Clean complete"

  run:
    desc: Build and run the binary
    deps:
      - build
    cmds:
      - ./{{.BINARY_NAME}}

  # Convenience alias for test:coverage
  cov:
    desc: Alias for test:coverage
    cmds:
      - task: test:coverage
